Fix `Style/ConditionalAssignment` cop error on `unless` without `else` and `assign_inside_condition` enforced style
If `Style/ConditionalAssignment` cop is configured with `assign_inside_condition` enforced style and `unless` node
does not have `else` branch and error occurs.

```console
NoMethodError:
       undefined method `begin_type?' for nil
     Shared Example Group: "single line condition autocorrect" called from ./spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb:920
     # ./lib/rubocop/cop/style/conditional_assignment.rb:312:in `any?'
     # ./lib/rubocop/cop/style/conditional_assignment.rb:312:in `allowed_single_line?'
     # ./lib/rubocop/cop/style/conditional_assignment.rb:293:in `check_assignment_to_condition'
     # ./lib/rubocop/cop/style/conditional_assignment.rb:236:in `block (2 levels) in <class:ConditionalAssignment>'
```