Change behavior when arg for run `rake new_cop` is incorrect
When usage was incorrect, I think that it is more user-friendly to show
usage.

Before

```console
% bundle exec rake new_cop
rake aborted!
ArgumentError: One argument is required
tasks/new_cop.rake:8:in `block (2 levels) in <top (required)>'
tasks/new_cop.rake:7:in `block in <top (required)>'
/Users/koic/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/Users/koic/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => new_cop
(See full trace by running task with --trace)
```

After

```console
% bundle exec rake new_cop
usage: bundle exec rake new_cop[Department/Name]
```

How to use commands is in accordance with the following manual.
https://github.com/bbatsov/rubocop/blob/v0.50.0/manual/development.md