Fix an error when using `changed_parameters` by external library
This PR fixes the following error when using `changed_parameters` in obsoletion.yml
by external library.

```console
NoMethodError: undefined method `merge' for
[{"cops"=>["Layout/SpaceAroundOperators", "Style/SpaceAroundOperators"],
"parameters"=>"MultiSpaceAllowedForOperators", "reason"=>"If your
intention was to allow extra spaces for alignment, please use `AllowFoy

          first.merge(second)
               ^^^^^^
/Users/koic/src/github.com/rubocop/rubocop-rails/lib/rubocop/rails/inject.rb:11:in `new'
/Users/koic/src/github.com/rubocop/rubocop-rails/lib/rubocop/rails/inject.rb:11:in `defaults!'
/Users/koic/src/github.com/rubocop/rubocop-rails/lib/rubocop-rails.rb:13:in `<top (required)>'
```