Improve examples of `Rails/SkipsModelValidations` cop
Follow up of #5592.

`update_attributes` will be deprecated in Rails 6.0.
This PR changed to indicate `update` instead of `update_attributes`
according to `RailsActiveRecordAliases` cop.

Also fixed because the number of arguments of `update_attribute`
was wrong.

```console
> Model.update_attribute(attr: 'value')
ArgumentError: wrong number of arguments (given 1, expected 2)
```