Fix `Style/ItBlockParameter` cop error on `Always` style and missing block body
For `->(_) {}`:

```shell
Failures:

  1) RuboCop::Cop::Style::ItBlockParameter >= Ruby 3.4 EnforcedStyle: always does not register an offense for block with parameter and missing body
     Failure/Error:
       node.body.each_descendant(:lvar).select do |descendant|
         descendant.source == block_argument_name
       end

     NoMethodError:
       undefined method 'each_descendant' for nil
```