[Fix #10780] Fix an error when using `rubocop:auto_correct` rake task
Fixes #10780.

This commit fixes the following error when using `rubocop:auto_correct`
deprecated custom rake task.

```console
% bundle exec rake lint:rubocop:auto_correct
rake aborted!
NoMethodError: undefined method `Rainbow' for
#<RuboCop::RakeTask:0x000000010b7a9020 @name=:rubocop, @verbose=true,
@fail_on_error=true, @patterns=[], @requires=[], @options=[], @formatters=[]>

          warn Rainbow(
               ^^^^^^^
```

And it fixes the following error that occur after that.

```console
% bundle exec rake lint:rubocop:auto_correct
rubocop:auto_correct task is deprecated; use rubocop:autocorrect task or
rubocop:autocorrect_all task instead.
rake aborted!
Don't know how to build task 'rubocop:autocorrect' (See the list of
available tasks with `rake --tasks`)
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/rake_task.rb:81:in
`block (2 levels) in setup_subtasks'
/Users/koic/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/koic/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => lint:rubocop:auto_correct
(See full trace by running task with --trace)
```