Allow `RuboCop::ConfigLoader.inject_defaults!` to accept `Pathname` instances
When using `Pathname` instance as an argument for `RuboCop::ConfigLoader.inject_defaults!`:

```ruby
project_root = Pathname.new(__dir__).join('..')
RuboCop::ConfigLoader.inject_defaults!(project_root.join('config', 'default.yml'))
```

The following error occurs:

```console
An error occurred while loading spec_helper.
Failure/Error: RuboCop::ConfigLoader.inject_defaults!(project_root.join('config', 'default.yml'))

NoMethodError:
  undefined method `start_with?' for #<Pathname:0x00007f91f62406c8>
# /Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/path_util.rb:46:in `smart_path'
# /Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/config_loader.rb:249:in `check_duplication'
# /Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/config_loader.rb:82:in `load_yaml_configuration'
# /Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/config_loader.rb:184:in `inject_defaults!'
# ./spec/spec_helper.rb:7:in `<top (required)>'
```

Investigating this error requires knowledge of RuboCop's internal implementation, which makes it difficult for users to troubleshoot.
The simplest solution is to restore support for `Pathname` instance, maintaining the previous (private API period) behavior.