Add a validation for supported styles other than EnforcedStyle
I added a validation for supported styles other than EnforcedStyle.

Problem
======

Currently, EnforcedStyle value is validated by SupportedStyles.

e.g.

```sh
$ cat .rubocop.yml
Style/AlignParameters:
  EnforcedStyle: aaaaaaaaaaaaaaaaaaaaaa
$ rubocop
Error: invalid EnforcedStyle 'aaaaaaaaaaaaaaaaaaaaaa' for Style/AlignParameters found in /tmp/tmp.SyHaGtdT0U/.rubocop.yml
Valid choices are: with_first_parameter, with_fixed_indentation
```

However, other styles aren't validated.

e.g.

```sh
$ cat .rubocop.yml
Style/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: aaaaaaaaaaaaaaaaaaaaaa
$ rubocop
Inspecting 0 files

0 files inspected, no offenses detected
```

Goal
======

Validate the invalid value.

e.g.

```sh
$ cat .rubocop.yml
Style/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: aaaaaaaaaaaaaaaaaaaaaa
$ rubocop
Error: invalid EnforcedStyleInsidePipes 'aaaaaaaaaaaaaaaaaaaaaa' for Style/SpaceAroundBlockParameters found in /tmp/tmp.SyHaGtdT0U/.rubocop.yml
Valid choices are: space, no_space
```

Changes
=====

- Add validation for styles other than `EnforcedStyle`
  - And rename some `SupportedStyles` names to match EnforcedStyle name
    - e.g. `SupportedStyles` to `SupportedStylesInsidePipes` (for `EnforcedStyleInsidePipes`)
- Add `SupportedStyles` for missing styles in config/default.yml
- Add a spec to check existence of `SupportedStyles` into `project_spec.rb`
- Add test cases to check validation