Change warning location of `SafeMode`
### Summary

Related https://github.com/rubocop-hq/rubocop/pull/7249.

In #7249, the following deprecation  warning is displayed for all
operations of `rubocop` command.

```console
% bundle exec rubocop -v
The `SafeMode` option will be removed in `RuboCop` 0.76. Please update
`rubocop-performance` to 1.5.0 or higher.
0.74.0
```

I noticed that with the `ConfigObsolete` module, RuboCop can only show
the warning when using `SafeMode`.

```console
% cat .rubocop.yml
require: rubocop-performance

Performance/Count:
  SafeMode: false

% bundle exec rubocop
Error: obsolete parameter SafeMode (for Performance/Count) found in .rubocop.yml
`SafeMode` has been removed. Use `SafeAutoCorrect` instead.
```

OTOH, RuboCop Performance happens the following error when `SafeMode`
module will removed:

```console
NameError:
 uninitialized constant RuboCop::Cop::Performance::Count::SafeMode
```

Therefore, the following milestones were planned. This plan does not
remove `SafeMode` module immediately.

- RuboCop 0.75 ... Presents an alternative API via `ConfigObsolete` module
- RuboCop 0.76 ... Remove SafeMode

This is probably a better way, as it is best to offer an alternative API
in the 3rd party module.

### Other Information

`Metrics/ClassLength` cop excludes config_obsoletion.rb by .rubocop.yaml
because most of the code in `ConfigObsoletion` module are configuration codes.

```console
% bundle exec rake internal_investigation

(snip)

Offenses:

lib/rubocop/config_obsoletion.rb:5:3: C: Metrics/ClassLength: Class has
too many lines. [185/182]
  class ConfigObsoletion ...
    ^^^^^^^^^^^^^^^^^^^^^^

1101 files inspected, 1 offense detected
RuboCop failed!
```