Fix an error for `rake slow_cops`
RuboCop will be inspected by a remote process when using `rubocop --server`.
As a result `RuboCop::Cop::Commissioner#trigger_responding_cops` is nothing:

```console
% rake prof:slow_cops
stackprof tmp/stackprof.dump --text --method
'RuboCop::Cop::Commissioner#trigger_responding_cops' rake aborted!
NoMethodError: undefined method `first' for nil:NilClass
tasks/prof.rake:28:in `block (2 levels) in <top (required)>'
Tasks: TOP => prof:slow_cops
```

This commit is inspected by a local process to prevent the above error.