Fix `Layout/LineLength` cop failure in case of tabbed YARD-comment-like string.
The following ruby code leads to an error:

rubocop -c <(echo "Layout/LineLength:\n AllowURI: true\n Max: 1") --stdin bug.rb --only Layout/LineLength -d <<EOF
  expect(some_exception_variable) {|e| e.url.should == 'http://host/path'}
EOF

(there's a `\t` in the beginning)

Backtrace:

```
An error occurred while Layout/LineLength cop was inspecting bug.rb.
undefined method `offset' for nil
lib/rubocop/cop/mixin/line_length_help.rb:76:in `extend_uri_end_position'
lib/rubocop/cop/mixin/line_length_help.rb:44:in `find_excessive_uri_range'
lib/rubocop/cop/layout/line_length.rb:359:in `check_uri_line'
lib/rubocop/cop/layout/line_length.rb:258:in `check_line'
lib/rubocop/cop/layout/line_length.rb:103:in `block in on_investigation_end'
lib/rubocop/cop/layout/line_length.rb:102:in `each'
lib/rubocop/cop/layout/line_length.rb:102:in `each_with_index'
lib/rubocop/cop/layout/line_length.rb:102:in `on_investigation_end'
```