Show alternative for obsolete EnforcesStyle parameter name
This PR shows alternative for obsolete EnforcesStyle parameter name.

For example, `EnforcedStyle: rails` in config/default.yml will be
replaced by `EnforcedStyle: outdented_access_modifiers`.

```diff
 # .rubocop.yml
 Layout/IndentationConsistency:
-  EnforcedStyle: rails
+  EnforcedStyle: outdented_access_modifiers
```

### Before

After `EnforcedStyle: rails` has been obsoleted, Users do not know
what the parameter name to replace.

```consle
% rubocop
Error: invalid EnforcedStyle 'rails' for Layout/IndentationConsistency
found in .rubocop.yml
Valid choices are: normal, outdented_access_modifiers
```

### After

Users will find that they should use `EnforcedStyle: outdented_access_modifiers` instead.

```console
% rubocop
Error: obsolete `EnforcedStyle: rails` (for Layout/IndentationConsistency)
found in .rubocop.yml
`EnforcedStyle: rails` has been renamed to `EnforcedStyle: outdented_access_modifiers`
```