Remove the undefined `TimeZone#strftime` from `Rails/TimeZone`
Follow up of https://github.com/bbatsov/rubocop/pull/5381#discussion_r159365679.

It seems that there is a mistake in solving the Issue below.

https://github.com/bbatsov/rubocop/issues/1773

From Rails 4.2 to Rails 5.2 (beta), The following code will result in an error.

```console
> str = '2015-03-02 19:05:37'
> Time.zone.strftime(str, "%Y-%m-%d %H:%M%Z")
NoMethodError: undefined method `strftime' for #<ActiveSupport::TimeZone:0x00007fdaed438c88>
```

AFIAK, `ActiveSupport::TimeZone#strftime` does not exist in Rails 4.2 at least.

Previously, #1773 was thought to mistype `Time.zone.strftime` to
`Time.zone.strptime`. However, I think that it was false positives
because `ActiveSupport::TimeZone#strptime` introduced in Rails 5.0
does not exist in Rails 4.2.

https://github.com/rails/rails/commit/a5e507fa0b8180c3d97458a9b86c195e9857d8f6

In this PR, `ActiveSupport::TimeZone#strftime` which does not exist is
removed from detection targets.

I'm judging that this change has no effect on codes that works as expected.