Add new `Rails/BulkChangeTable` cop
This Cop checks whether alter queries are combinable.
If combinable queries are detected, it suggests to you to use
`change_table` with `bulk: true` instead.
When use this method, make combinable alter queries a bulk alter query.

The `bulk` option is only supported on the MySQL and the PostgreSQL
(5.2 later) adapter; thus it will automatically detect an adapter from
`development` environment in `config/database.yml` when the `Database`
option is not set. If the adapter is not `mysql2` or `postgresql`, this
Cop ignores offenses.

For example, the following migration executes 4 SQLs:

```ruby
class BulkExample < ActiveRecord::Migration[5.2]
  def change
    // Output SQL
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    add_reference :users, :team
    add_column :users, :name, :string, null: false
    add_column :users, :nickname, :string
  end
end
```

```
== 20180513070748 BulkExample: migrating ======================================
-- add_reference(:users, :team)
D, [2018-05-13T16:19:09.247167 #88149] DEBUG -- :    (173.7ms)  ALTER TABLE `users` ADD `team_id` bigint
D, [2018-05-13T16:19:09.248363 #88149] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:5
D, [2018-05-13T16:19:09.279004 #88149] DEBUG -- :    (29.2ms)  CREATE  INDEX `index_users_on_team_id`  ON `users` (`team_id`)
D, [2018-05-13T16:19:09.279818 #88149] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:5
   -> 0.2073s
-- add_column(:users, :name, :string, {:null=>false})
D, [2018-05-13T16:19:09.339642 #88149] DEBUG -- :    (59.1ms)  ALTER TABLE `users` ADD `name` varchar(255) NOT NULL
D, [2018-05-13T16:19:09.339814 #88149] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:6
   -> 0.0596s
-- add_column(:users, :nickname, :string)
D, [2018-05-13T16:19:09.386546 #88149] DEBUG -- :    (46.2ms)  ALTER TABLE `users` ADD `nickname` varchar(255)
D, [2018-05-13T16:19:09.387489 #88149] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:7
   -> 0.0476s
== 20180513070748 BulkExample: migrated (0.3151s) =============================
```

If you use `bulk: true`, it combines into 3 SQLs.

```ruby
class BulkExample < ActiveRecord::Migration[5.2]
  def change
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    add_reference :users, :team
    change_table :users, bulk: true do |t|
      t.string :name, null: false
      t.string :nickname
    end
  end
end
```

```
== 20180513070748 BulkExample: migrating ======================================
-- add_reference(:users, :team)
D, [2018-05-13T16:26:35.937416 #89967] DEBUG -- :    (70.5ms)  ALTER TABLE `users` ADD `team_id` bigint
D, [2018-05-13T16:26:35.937644 #89967] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:5
D, [2018-05-13T16:26:35.974410 #89967] DEBUG -- :    (34.1ms)  CREATE  INDEX `index_users_on_team_id`  ON `users` (`team_id`)
D, [2018-05-13T16:26:35.974609 #89967] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:5
   -> 0.1083s
-- change_table(:users, {:bulk=>true})
D, [2018-05-13T16:26:36.030428 #89967] DEBUG -- :    (52.1ms)  ALTER TABLE `users` ADD `name` varchar(255) NOT NULL, ADD `nickname` varchar(255)
D, [2018-05-13T16:26:36.030584 #89967] DEBUG -- :   ↳ db/migrate/20180513070748_bulk_example.rb:6
   -> 0.0557s
== 20180513070748 BulkExample: migrated (0.1644s) =============================
```

By the way, this Cop ignores non-combinable queries such as
`add_references` because including these in bulk changes will
cause an error like the following:

```
== 20180513070748 BulkExample: migrating ======================================
-- change_table(:users, {:bulk=>true})
D, [2018-05-13T16:30:52.348856 #90767] DEBUG -- :    (0.4ms)  SELECT RELEASE_LOCK('5518437444551514000')
D, [2018-05-13T16:30:52.349985 #90767] DEBUG -- :   ↳ /Users/watanabekazuma/.rbenv/versions/2.4.1/bin/rake:22
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Unknown method called : add_reference_for_alter([:team, {}])
```