[Fix #6089] Make `Rails/BulkChangeTable` aware of variable table name
Fixes #6089

The following error is occurred when using variables as table name:

```
NoMethodError:
       undefined method `value' for s(:lvar, :table):RuboCop::AST::Node
     # ./lib/rubocop/cop/rails/bulk_change_table.rb:258:in `process'
     # ./lib/rubocop/cop/rails/bulk_change_table.rb:144:in `block in on_def'
     # ./lib/rubocop/ast/node.rb:185:in `block in each_child_node'
     # ./lib/rubocop/ast/node.rb:183:in `each'
     # ./lib/rubocop/ast/node.rb:183:in `each_child_node'
     # ./lib/rubocop/cop/rails/bulk_change_table.rb:142:in `on_def'
     # ./lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
     # ./lib/rubocop/cop/commissioner.rb:105:in `with_cop_error_handling'
     # ./lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
     # ./lib/rubocop/cop/commissioner.rb:55:in `each'
     # ./lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
     # ./lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
     # ./lib/rubocop/ast/traversal.rb:12:in `walk'
     # ./lib/rubocop/cop/commissioner.rb:45:in `investigate'
     # ./lib/rubocop/rspec/cop_helper.rb:71:in `_investigate'
     # ./lib/rubocop/rspec/cop_helper.rb:25:in `inspect_source'
     # ./lib/rubocop/rspec/expect_offense.rb:61:in `expect_no_offenses'
     # ./spec/rubocop/cop/rails/bulk_change_table_spec.rb:358:in `block (3 levels) in <top (required)>'
```

This problem occurs because the table name is not a literal node.
It is very difficult to interpolate variables, so in that case
this cop ignores such nodes.