Fix an error for `Style/SingleLineMethods`
This PR fixes the following error for `Style/SingleLineMethods`.

```console
% cat  example.rb
def some_method; 42 end

% bundle exec rubocop --only Style/SingleLineMethods -d

(snip)

undefined method `arguments' for s(:int, 42):RuboCop::AST::IntNode
Did you mean?  argument?
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/single_line_methods.rb:118:in `method_body_source'
```

This is a regression of #9704.