Fix an error for `Lint/EmptyConditionalBody`
This PR fixes an error for `Lint/EmptyConditionalBody`
when missing `if` body and using method call for return value.

```ruby
if condition
end.do_something
```

```console
% rubocop lint_empty_conditional_body.rb --only Lint/EmptyConditionalBody -d
(snip)

undefined method `loc' for :do_something:Symbol
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/mixin/comments_help.rb:72:in `find_end_line'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/mixin/comments_help.rb:20:in `comments_in_range'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/mixin/comments_help.rb:15:in `contains_comments?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/empty_conditional_body.rb:72:in `on_if'
```