Workaround for CI build error when using Bundler 2.2.5 on Windows
This PR is a workaround for `undefined method `add_dependency_names' for nil:NilClass`
CI build error when using Bundler 2.2.25 on Windows.

```console
Failures:

  1) RuboCop::Lockfile#gems returns all the dependencies
     Failure/Error: @parser = lockfile ?
     Bundler::LockfileParser.new(lockfile) : nil

     NoMethodError:
       undefined method `add_dependency_names' for nil:NilClass
     # ./lib/rubocop/lockfile.rb:35:in `new'
     # ./lib/rubocop/lockfile.rb:35:in `parser'
     # ./lib/rubocop/lockfile.rb:17:in `gems'
     # ./spec/rubocop/lockfile_spec.rb:77:in `block (3 levels) in
       <top (required)>'
     # ./spec/rubocop/lockfile_spec.rb:79:in `block (3 levels) in
       <top (required)>'
  4) RuboCop::Lockfile#includes_gem? for an included dependency
     Failure/Error: @parser = lockfile ?
       Bundler::LockfileParser.new(lockfile) : nil

     NoMethodError:
       undefined method `add_dependency_names' for nil:NilClass
     # ./lib/rubocop/lockfile.rb:35:in `new'
     # ./lib/rubocop/lockfile.rb:35:in `parser'
     # ./lib/rubocop/lockfile.rb:17:in `gems'
     # ./lib/rubocop/lockfile.rb:25:in `includes_gem?'
     # ./spec/rubocop/lockfile_spec.rb:95:in `block (3 levels) in
       <top (required)>'
     # ./spec/rubocop/lockfile_spec.rb:100:in `block (4 levels) in
       <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (4 levels) in
       <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `chdir'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (3 levels) in
       <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block (2 levels) in
       <top (required)>'
     # tasks/spec_runner.rake:32:in `block in run_specs'
     # tasks/spec_runner.rake:44:in `with_encoding'
     # tasks/spec_runner.rake:28:in `run_specs'
     # tasks/spec_runner.rake:115:in `block in <top (required)>'

  5) RuboCop::Lockfile#dependencies returns all the dependencies
     Failure/Error: @parser = lockfile ?
     Bundler::LockfileParser.new(lockfile) : nil

     NoMethodError:
       undefined method `add_dependency_names' for nil:NilClass
     # ./lib/rubocop/lockfile.rb:35:in `new'
     # ./lib/rubocop/lockfile.rb:35:in `parser'
     # ./lib/rubocop/lockfile.rb:10:in `dependencies'
     # ./spec/rubocop/lockfile_spec.rb:59:in `block (3 levels) in
       <top (required)>'
     # ./spec/rubocop/lockfile_spec.rb:61:in `block (3 levels) in
       <top (required)>'
     # ./spec/rubocop/lockfile_spec.rb:66:in `block (3 levels) in
       <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (4 levels) in
       <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `chdir'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (3 levels) in
       <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block (2 levels) in
       <top (required)>'
     # tasks/spec_runner.rake:32:in `block in run_specs'
     # tasks/spec_runner.rake:44:in `with_encoding'
     # tasks/spec_runner.rake:28:in `run_specs'
     # tasks/spec_runner.rake:115:in `block in <top (required)>'

Finished in 4 minutes 9 seconds (files took 3.81 seconds to load)
16350 examples, 5 failures, 14 pending

Failed examples:

rspec ./spec/rubocop/lockfile_spec.rb:83 # RuboCop::Lockfile#gems
returns all the dependencies
rspec ./spec/rubocop/lockfile_spec.rb:112 #
RuboCop::Lockfile#includes_gem? for an excluded gem
rspec ./spec/rubocop/lockfile_spec.rb:106 #
RuboCop::Lockfile#includes_gem? for an included gem
rspec ./spec/rubocop/lockfile_spec.rb:100 #
RuboCop::Lockfile#includes_gem? for an included dependency
rspec ./spec/rubocop/lockfile_spec.rb:65 #
RuboCop::Lockfile#dependencies returns all the dependencies
```

https://github.com/rubocop/rubocop/runs/3211951622

It may be affected by the following Bundler's changes.

bundler/lib/bundler/lockfile_parser.rb:

```diff
        platform = platform ? Gem::Platform.new(platform) :
        Gem::Platform::RUBY
        @current_spec = LazySpecification.new(name, version, platform)
        @current_spec.source = @current_source
+       @current_source.add_dependency_names(name)

        @specs[@current_spec.identifier] = @current_spec
      elsif spaces.size == 6
```

https://github.com/rubygems/rubygems/pull/4782