Fix an error for `Style/GuardClause`
This PR fixes the following error for `Style/GuardClause`
when using heredoc as an argument of raise in `then` branch
and it does not have `else` branch:

```ruby
def func
  if condition
    raise <<~MESSAGE
      oops
    MESSAGE
  end
end
```

```console
% bundle exec rubocop --only Style/GuardClause -d
(snip)

An error occurred while Style/GuardClause cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/guard_clause/example.rb:1:0.
undefined method `source_range' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/guard_clause.rb:209:in `autocorrect_heredoc_argument'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/guard_clause.rb:191:in `autocorrect'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/guard_clause.rb:179:in `block in register_offense'
```