Explicitly use RSpec namespace in external top level shared_*
If lib/rubocop/rspec/shared_contexts.rb and lib/rubocop/rspec/shared_examples.rb
are required after RSpec has been set to not expose the DSL globally,
then you will get the following error:

NoMethodError:
  undefined method `shared_context' for main:Object

This change does not negatively affect users who still expose the DSL
globally.