Use RuboCop RSpec 3.0 for development
This commit uses RuboCop RSpec 3.0 and resolves the following new error:

```console
$ bundle exec rubocop
Error: The `RSpec/FilePath` cop has been split into `RSpec/SpecFilePathFormat` and `RSpec/SpecFilePathSuffix`.
(obsolete configuration found in .rubocop.yml, please update it)
```

Also fixes the following test failure:

```console
$ bundle exec rspec './spec/rubocop/version_spec.rb[1:2:6:1]'
Run options: include {:ids=>{"./spec/rubocop/version_spec.rb"=>["1:2:6:1"]}}

Randomized with seed 33108
F

Failures:

  1) RuboCop::Version.extension_versions with all known mappings returns the extensions
     Failure/Error:
       expect(extension_versions).to contain_exactly(
         /- rubocop-performance \d+\.\d+\.\d+/,
         /- rubocop-rspec \d+\.\d+\.\d+/,
         /- rubocop-graphql \d+\.\d+\.\d+/,
         /- rubocop-md \d+\.\d+\.\d+/,
         /- rubocop-thread_safety \d+\.\d+\.\d+/,
         /- rubocop-capybara \d+\.\d+\.\d+/,
         /- rubocop-factory_bot \d+\.\d+\.\d+/,
         /- rubocop-rspec_rails \d+\.\d+\.\d+/
       )

       expected collection contained:  [/- rubocop-performance \d+\.\d+\.\d+/, /- rubocop-rspec \d+\.\d+\.\d+/,
/- rubocop-graphql \d+\.\d+\...pybara \d+\.\d+\.\d+/, /- rubocop-factory_bot \d+\.\d+\.\d+/, /- rubocop-rspec_rails \d+\.\d+\.\d+/]
       actual collection contained:    ["  - rubocop-graphql 1.0.0", "  - rubocop-md 1.0.0", "  - rubocop-performance 1.21.0",
"  - rubocop-rspec 3.0.0", "  - rubocop-rspec_rails 2.28.2", "  - rubocop-thread_safety 1.0.0"]
       the missing elements were:      [/- rubocop-capybara \d+\.\d+\.\d+/, /- rubocop-factory_bot \d+\.\d+\.\d+/]
     # ./spec/rubocop/version_spec.rb:151:in `block (4 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:54:in `block (3 levels) in <top (required)>'
     # ./lib/rubocop/cop/registry.rb:35:in `with_temporary_global'
     # ./lib/rubocop/rspec/shared_contexts.rb:54:in `block (2 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:44:in `block (2 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `block (4 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `chdir'
     # ./lib/rubocop/rspec/shared_contexts.rb:29:in `block (3 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.03052 seconds (files took 1.51 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/rubocop/version_spec.rb:150 # RuboCop::Version.extension_versions with all known mappings returns the extensions
```