[Fix #7953] Fix an error for `Lint/AmbiguousOperator`
Fixes #7953.

This PR fixes the following error for `Lint/AmbiguousOperator`
when a method with no arguments is used in advance.

```console
% cat example.rb
foo
bar +1

% bundle exec rubocop --only Lint/AmbiguousOperator -d
(snip)

An error occurred while Lint/AmbiguousOperator cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7953/example.rb.
undefined method `source_range' for nil:NilClass
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/lint/ambiguous_operator.rb:75:in
`offense_position?'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/lint/ambiguous_operator.rb:63:in
`block in find_offense_node_by'
```