Fix undefined method `status' for #<RuboCop::ConfigNotFoundError> (NoMethodError)
```
$ rubocop -c file_that_does_not_exist.yml foo.rb
Configuration file not found: /Users/onaka/src/github.com/bbatsov/rubocop/file_that_does_not_exist.yml
Traceback (most recent call last):
        6: from /Users/onaka/.gem/ruby/2.6.0/bin/rubocop:23:in `<main>'
        5: from /Users/onaka/.gem/ruby/2.6.0/bin/rubocop:23:in `load'
        4: from /Users/onaka/.gem/ruby/2.6.0/gems/rubocop-0.53.0/bin/rubocop:12:in `<top (required)>'
        3: from /opt/rubies/2.6.0-dev/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
        2: from /Users/onaka/.gem/ruby/2.6.0/gems/rubocop-0.53.0/bin/rubocop:13:in `block in <top (required)>'
        1: from /Users/onaka/.gem/ruby/2.6.0/gems/rubocop-0.53.0/lib/rubocop/cli.rb:36:in `run'
/Users/onaka/.gem/ruby/2.6.0/gems/rubocop-0.53.0/lib/rubocop/cli.rb:44:in `rescue in run': undefined method `status' for #<RuboCop::ConfigNotFoundError:0x00007fd0b808e040> (NoMethodError)
```