Fix an error for `Style/Semicolon`
This PR fixes the following error for `Style/Semicolon`
when using a comment containing a semicolon before a block:

```ruby
# ;
foo {
}
```

```console
% bundle exec rubocop --only Style/Semicolon
(snip)

  NoMethodError:
    undefined method `semicolon?' for nil:NilClass
```

No changelog entry because this is a bug by #11465 and not released.