Fix `Style/RedundantLineContinuation` cop error on multiline assignment
```bash
$ cat /tmp/ruby.rb
a, b, \
 c = [1, 2, 3]
```

```bash
bundle exec rubocop /tmp/ruby.rb --only Style/RedundantLineContinuation -d

For /tmp: An error occurred while Style/RedundantLineContinuation cop was inspecting /tmp/ruby.rb.
undefined method `parenthesized_call?' for an instance of Symbol
lib/rubocop/cop/style/redundant_line_continuation.rb:187:in `argument_newline?'
lib/rubocop/cop/style/redundant_line_continuation.rb:143:in `redundant_line_continuation?'
lib/rubocop/cop/style/redundant_line_continuation.rb:91:in `block in on_new_investigation'
lib/rubocop/cop/mixin/match_range.rb:14:in `block in each_match_range'
lib/rubocop/cop/mixin/match_range.rb:14:in `scan'
lib/rubocop/cop/mixin/match_range.rb:14:in `each_match_range'
lib/rubocop/cop/style/redundant_line_continuation.rb:89:in `on_new_investigation'
```

The `node = node.to_a.last if node.assignment?` expression was introduced
in https://github.com/rubocop/rubocop/pull/12678, but ATM there are no tests
hitting that line. Perhaps that was unintentional?

Without this line, tests are passing