[Fix #4646] Make `Lint/Debugger` aware of `Kernel` and cbase
`binding`, `debugger` and `byebug` is a `Kernel` method. Therefore those methods are callable with `Kernel` receiver expressly.

```bash
binding.pry        # => start a pry
Kernel.binding.pry # => start a pry
```

`save_and_open_page` and others are not defined in `Kernel`. Therefore those method is not callable with `Kernel` receiver.

```
     Failure/Error: Kernel.save_and_open_screenshot

     NoMethodError:
       undefined method `save_and_open_screenshot' for Kernel:Module
```

And this change makes the cop aware of `cbase`.

```ruby
Pry == ::Pry
```