Workaround for Parser 3.2.2.2 or lower with Ruby 3.3.0dev
Follow up https://github.com/ruby/ruby/pull/7877.

Ruby 3.3.0dev is set to promote Racc to a bundled gem.
Therefore, this PR provides a workaround for Parser 3.2.2.2 or lower with Ruby 3.3.0dev
to prevents the following Ruby 3.3.0dev CI matrix error:

```console
bundle exec rake internal_investigation

rake aborted!
LoadError: cannot load such file -- racc/parser
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/parser-3.2.2.1/lib/parser.rb:12:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/rubocop-ast-1.29.0/lib/rubocop/ast.rb:3:in `<top (required)>'
/usr/local/bundle/gems/rubocop-ast-1.29.0/lib/rubocop-ast.rb:3:in `require_relative'
/usr/local/bundle/gems/rubocop-ast-1.29.0/lib/rubocop-ast.rb:3:in `<top (required)>'
```

https://app.circleci.com/pipelines/github/rubocop/rubocop/9387/workflows/c308ef87-1373-4c0a-b90d-a22ea57860e3/jobs/279345

I opened PR https://github.com/whitequark/parser/pull/929 to add Racc as a runtime dependency to the Parser gem.
When the Praser gem releases a new version of Racc that includes the runtime dependencies,
it will be able to upgrade the Parser gem dependency and remove the workaround.

RuboCop's support for Ruby 3.3.0dev is experimental and additions of Racc to the runtime have not been made,
as I believe the solution proposed in https://github.com/whitequark/parser/pull/929 is the best.