Fix an error for `Style/RequireOrder`
This PR fixes the following error for `Style/RequireOrder`
when only one `reuqire`.

```ruby
require 'a'
```

```console
% bundle exec rubocop example.rb --only Style/RequireOrder -d
(snip)

undefined method `if_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/require_order.rb:102:in `not_modifier_form?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/require_order.rb:85:in `on_send'
```