Fix an error for `Style/AccessModifierDeclarations` when if a non method definition was included
This PR is fix an error for `Style/AccessModifierDeclarations` when if a non method definition was included.

## Code to reproduce
```ruby
class Test
  private def foo; end
  private def bar; end
  def baz; end
  QUX = ['qux']
end
```

## Occurring Error
```
Failures:

  1) RuboCop::Cop::Style::AccessModifierDeclarations when `group` is configured offends when multiple groupable access modifiers are defined
     Failure/Error: sibling.method?(node.method_name) && !sibling.arguments.empty?

     NoMethodError:
       undefined method `method?' for s(:casgn, nil, :QUX,
         s(:array)):RuboCop::AST::CasgnNode
```