Fix an error for `Style/ClassMethodsDefinitions`
This PR fixes the following error for `Lint/ClassMethodsDefinitions`
when defining class methods with `class << self` with comment only body.

```console
% cat /tmp/example.rb
class Foo
  class << self
    def do_something
      # TODO
    end
  end
end

% rubocop /tmp/example.rb --only Style/ClassMethodsDefinitions -d
For /private/tmp: Default configuration from
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/config/default.yml
Inspecting 1 file
Scanning /private/tmp/example.rb
An error occurred while Style/ClassMethodsDefinitions cop was inspecting
/private/tmp/example.rb:2:2.
undefined method `gsub' for nil:NilClass
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/
class_methods_definitions.rb:147:in `extract_def_from_sclass'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/
class_methods_definitions.rb:120:in `block in autocorrect_sclass'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/
class_methods_definitions.rb:117:in `each'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/
class_methods_definitions.rb:117:in `autocorrect_sclass'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/
class_methods_definitions.rb:77:in `block in on_sclass'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/base.rb:340:in
`correct'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/base.rb:127:in
`add_offense'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/
class_methods_definitions.rb:76:in `on_sclass'
(snip)

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/ClassMethodsDefinitions cop was inspecting
/private/tmp/example.rb:2:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.11.0 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-darwin19)
Finished in 0.07133800000883639 seconds
```