Make `Style/CollectionCompact` aware of `delete_if`
This PR makes `Style/CollectionCompact` aware of `delete_if`.

Note, `Enumerator` does not have `delete_if`, the following use case are allowed:

```ruby
% ruby -ve '[1, 2, 3].to_enum.delete_if { |e| e.nil? }'
ruby 3.3.0dev (2023-03-17T00:50:41Z master f29c9d6d36) [x86_64-darwin19]
-e:1:in `<main>': undefined method `delete_if' for an instance of Enumerator (NoMethodError)

[1, 2, 3].to_enum.delete_if { |e| e.nil? }
                 ^^^^^^^^^^
```

It doesn't register an offense as well as `to_enum` when `lazy` is used.