[Fix #6917] Bump Bundler dependency to >= 1.15.0
Fixes #6917.

This PR bumps Bundler dependency to >= 1.15.0.

Bundler 2 has already been released.
This PR drops old Bundler versions (1.14 or lower) to prevent the following error.

## Bundler 1.14

An unexpected error occurs.

```console
% bundle _1.14.6_ exec rubocop
bundler: failed to load command:
rubocop (/Users/koic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/bin/rubocop)
TypeError: no implicit conversion of String into Integer
  /Users/koic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rubocop-0.67.1/exe/rubocop:16:in
  `<top (required)>'
  /Users/koic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/bin/rubocop:23:in
  `load'
  /Users/koic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/bin/rubocop:23:in
  `<top (required)>'
```

## Bundler 1.15

Errors does not occur as expected.

```console
% bundle _1.15.0_ exec rubocop
[Warn] Performance Cops will be removed from RuboCop 0.68. Use
rubocop-performance gem instead.
       https://github.com/rubocop-hq/rubocop/tree/master/manual/migrate_performance_cops.md

(snip)
```