Fix an error for `Style/YodaCondition`
This PR fixes an error for `Style/YodaCondition` when
equality check method is used without the first argument:

```ruby
foo.==
```

```console
% rubocop /tmp/example.rb --only Style/YodaCondition -d
(snip)

For /tmp: An error occurred while Style/YodaCondition cop was inspecting /tmp/example.rb:1:0.
undefined method `literal?' for nil:NilClass
An error occurred while Style/YodaCondition cop was inspecting /tmp/example.rb:1:0.
undefined method `literal?' for nil
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.53.1/lib/
rubocop/cop/style/yoda_condition.rb:144:in `constant_portion?'
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.53.1/lib/
rubocop/cop/style/yoda_condition.rb:126:in `valid_yoda?'
```