[Fix #7253] Fix an error for `Lint/NumberConversion`
Fixes #7253.

This PR fixes an error for `Lint/NumberConversion` when `#to_i` called without a
receiver.

```ruby
# example.rb
class Time
  def mod(modulus)
    to_i % modulus
  end
end
```

```console
% rubocop --only Lint/NumberConversion -d
For /Users/koic/src/github.com/koic/rubocop-issues/7253: configuration
from /Users/koic/src/github.com/koic/rubocop-issues/.rubocop.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.4.1/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.4.1/config/default.yml
Default configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-0.73.0/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.1.0/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.1.0/config/default.yml
Inspecting 1 file
Scanning /Users/koic/src/github.com/koic/rubocop-issues/7253/example.rb
An error occurred while Lint/NumberConversion cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7253/example.rb:3:4.
undefined method `source' for nil:NilClass
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-0.73.0/lib/rubocop/cop/lint/number_conversion.rb:48:in
`block in on_send'
```

This PR accepts `to_i` when called without a receiver.

As an alternative, I thought about auto-correcting to `Integer (self, 10)`.
However, type of `self` depends on the context.
For example, the following error occurs when `self` is a `Time` object:

```ruby
class Time
  def do_something
    Integer(self, 10)
  end
end

Time.new.do_something # ArgumentError (base specified for non string value)
```

This has the same meaning as:

```ruby
Integer(Time.new, 10) # ArgumentError (base specified for non string value)
```

So I decided to leave it as `#to_i` when a receiver wasn't called.