Fix the error happening with empty config sections
When a configuration section is empty like follow:
AllCops:
  RunRailsCops: true
Rails/HasAndBelongsToMany:

The config object contains a key/value association
with an empty (nil) value, which leads to an ugly exception:

  1) RuboCop::Config#validate when the configuration file includes an empty section does not raise validation error
     Failure/Error: expect { configuration.validate }.to_not raise_error
       expected no Exception, got #<NoMethodError: undefined method `each_key' for nil:NilClass> with backtrace:
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/lib/rubocop/config.rb:177:in `block in validate_parameter_names'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/lib/rubocop/config.rb:176:in `each'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/lib/rubocop/config.rb:176:in `validate_parameter_names'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/lib/rubocop/config.rb:111:in `validate'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/lib/rubocop/config.rb:80:in `warn_unless_valid'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/lib/rubocop/config_loader.rb:41:in `load_file'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/rubocop/config_spec.rb:20:in `block (3 levels) in <top (required)>'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/rubocop/config_spec.rb:84:in `block (5 levels) in <top (required)>'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/rubocop/config_spec.rb:84:in `block (4 levels) in <top (required)>'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/support/shared_contexts.rb:27:in `block (4 levels) in <top (required)>'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/support/shared_contexts.rb:26:in `chdir'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/support/shared_contexts.rb:26:in `block (3 levels) in <top (required)>'
         # /Users/alexandreignjatovic/Documents/perso/dev/rubocop/spec/support/shared_contexts.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/rubocop/config_spec.rb:84:in `block (4 levels) in <top (required)>'
     # ./spec/support/shared_contexts.rb:27:in `block (4 levels) in <top (required)>'
     # ./spec/support/shared_contexts.rb:26:in `chdir'
     # ./spec/support/shared_contexts.rb:26:in `block (3 levels) in <top (required)>'
     # ./spec/support/shared_contexts.rb:8:in `block (2 levels) in <top (required)>'

Instead of checking everywhere that the config sections are not
containing nil, I removed all empty section in the config loader.

I also added a spec test