Support Ruby 3.1's anonymous block argument syntax
Follow up to https://github.com/rubocop/rubocop-ast/pull/218.

This PR supports Ruby 3.1's anonymous block argument syntax and fixes the following error.

```console
% ruby -v
ruby 3.1.0dev (2021-12-01T02:00:10Z master 0b53a8895f) [x86_64-darwin19]

% echo 'def foo(&) = bar(&)' | be rubocop --enable-pending-cops --stdin example.rb
Inspecting 1 file
.

0 files inspected, no offenses detected
undefined method `type' for nil:NilClass
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:131:in
`on_block_pass'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/commissioner.rb:71:in
`on_block_pass'
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:159:in
`block in on_send'
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:156:in
`each'
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:156:in
`each_with_index'
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:156:in
`on_send'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/commissioner.rb:71:in `on_send'
```

This PR makes RuboCop require Parser 1.14 or higher Because this error resolved by
https://github.com/rubocop/rubocop-ast/pull/218.