[Fix #13331] Fix an error when using release task
Fixes #13331.

This PR fixes an error when using release task.

In Ruby 3.2 and later, this does not result in an error, but in Ruby 3.1 and earlier, the following error occurs.

```console
$ ruby -v
ruby 3.1.5p252 (2024-04-23 revision 1945f8dc0e) [x86_64-darwin23]

$ bundle exec rake cut_release:minor
Files:         687
Modules:        92 (   13 undocumented)
Classes:       649 (    4 undocumented)
Constants:    1197 ( 1181 undocumented)
Attributes:     37 (    0 undocumented)
Methods:      1504 ( 1309 undocumented)
 27.94% documented
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cops_documentation_generator.rb:321:
warning: Passing only keyword arguments to Struct#initialize will behave differently from Ruby 3.2.
Please use a Hash literal like .new({k: v}) instead of .new(k: v).
rake aborted!
NoMethodError: undefined method `none?' for nil:NilClass

    return if example_objects.none?
                             ^^^^^^
```

This is due to a change in the behavior of `Struct` in Ruby 3.2. To maintain compatibility with Ruby 3.1 and earlier, `keyword_init: true` is required.