[Fix #10269] Mark unsafe autocorrect for `Lint/IncompatibleIoSelectWithFiberScheduler`
Fixes #10269.

`Lint/IncompatibleIoSelectWithFiberScheduler`cop's autocorrection is unsafe because
`NoMethodError` occurs if `require 'io/wait'` is not called.

## `require 'io/wait'` is called

```console
% ruby -rio/wait -ve 'IO.new(IO.sysopen("/tmp")).wait_readable'
ruby 3.1.0dev (2021-11-21T10:23:36Z master 784f1e1538) [x86_64-darwin19]
```

## `require 'io/wait'` is not called

```console
% ruby -ve 'IO.new(IO.sysopen("/tmp")).wait_readable'
ruby 3.1.0dev (2021-11-21T10:23:36Z master 784f1e1538) [x86_64-darwin19]
-e:1:in `<main>': undefined method `wait_readable' for #<IO:fd 9> (NoMethodError)

IO.new(IO.sysopen("/tmp")).wait_readable
                          ^^^^^^^^^^^^^^
```