Fix config#check to use loaded_path in warning (#5278)
Due to a configuration refactor, the `#path` variable is no longer
available in `config#check`, which causes rubocop to crash with
`NameError: undefined local variable or method path` if the deprecation
check yields a deprecation warning.

This replaces the warning to use the instance variable `#loaded_path`
and adds a spec to cover the behavior.