Handle major version requirements in Gemspec/RequiredRubyVersion
It's possible to use `required_ruby_version` to allow all minor versions
of a particular major version of Ruby:

    spec.required_ruby_version = '~> 2'

Previously this would cause `Gemspec/RequiredRubyVersion` to crash with:

    undefined method `[]' for nil:NilClass
    lib/rubocop/cop/gemspec/required_ruby_version.rb:71:in `extract_ruby_version'

I've added docs and tests for the pessimistic operator, which otherwise
works well.