Restore a pending test for processing a regex with regopt
This PR reverts a pending test of #10432 because https://github.com/jruby/jruby/issues/7113
has been resolved in JRuby 9.3.9.0.

## JRuby 9.3.3.0

`RegexpError` error will occur:

```console
% rbenv local jruby-9.3.3.0
% ruby -e "Regexp.new('\x82', Regexp::NOENCODING)"
RegexpError: invalid multibyte escape: /\x82/
  initialize at org/jruby/RubyRegexp.java:956
         new at org/jruby/RubyClass.java:893
      <main> at -e:1
```

## JRuby 9.3.9.0 and JRuby 9.4.1.0

No errors:

```console
% rbenv local jruby-9.3.9.0
% ruby -e "Regexp.new('\x82', Regexp::NOENCODING)"

% rbenv local jruby-9.4.1.0
% ruby -e "Regexp.new('\x82', Regexp::NOENCODING)"
```