Fix an error for `Style/Copyright`
This PR fixes the following error for `Style/Copyright` when `AutocorrectNotice` is missing:

```console
$ cat .rubocop.yml
Style/Copyright:
  Enabled: true
  AutocorrectNotice: ~

$ bundle exec rubocop -d
(snip)

undefined method 'empty?' for nil
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/copyright.rb:61:
in 'RuboCop::Cop::Style::Copyright#verify_autocorrect_notice!'
```