Fix an error for `Style/Documentation`
This PR fixes an error for `Style/Documentation`
when namespace is a variable.

```ruby
m = Module.new
module n::N
  def method
  end
end
```

```console
% rubocop documentation.rb --only Style/Documentation -d
(snip)

undefined method `namespace' for s(:lvar, :m):RuboCop::AST::Node
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/documentation.rb:187:in `qualify_const'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/documentation.rb:187:in `qualify_const'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/documentation.rb:181:in `block in identifier'
```

It also complements missing cbase and namespaces in offense messages. e.g.:

```diff
 class ::MyClass
-^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class MyClass`.
+^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class ::MyClass`.
```

```diff
 class self::MyClass
-^^^^^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class MyClass`.
+^^^^^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class self::MyClass`.
```

```diff
 class my_method::MyClass
-^^^^^^^^^^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class MyClass`.
+^^^^^^^^^^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class my_method::MyClass`.
```